services:
  db:
    image: postgres
    restart: always
    container_name: fastapi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_v1
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@0.0.0.0:5432/fastapi_test"
    ports:
      - "8000:8000"

volumes:
  postgres_data: